spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
#   username: root
#   password: 111111
#   url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8
   username: qa
   password: ZPPtJmDoNixSqxT0
   url: jdbc:mysql://10.2.3.4:3306/mock?useUnicode=true&characterEncoding=UTF-8
   initialSize: 10
   maxActive: 20
   minIdle: 5
   maxWait: 6000
server:
  port: 17099

mybatis:
  mapper-locations: classpath:mapperXml/*.xml
  type-aliases-package: com.manage.model
